fruits = ("apple", "banana", "cherry", "mango", "grape")
print(fruits[0])   
print(fruits[1])    
print(fruits[4])
print(fruits[-1])   
print(fruits[-2])   
print(fruits[1:3])  
print(fruits[:3])   
print(fruits[2:])   
print(fruits[::2])  
print(fruits[::-1])