shopping_cart = ["Laptop","Mouse","Keyboard"]
print("Original Cart:")
print(shopping_cart)
shopping_cart.append("Headphone")
print("\nAfter append:")
print(shopping_cart)
shopping_cart.insert(1, "Mobile")
print("\nAfter insert:")
print(shopping_cart)
shopping_cart.extend(["Charger", "USB Cable"])
print("\nAfter extend:")
print(shopping_cart)
shopping_cart.remove("Mouse")
print("\nAfter remove:")
print(shopping_cart)
removed_item = shopping_cart.pop(2)
print("\nRemoved item using pop:")
print(removed_item)
print("After pop:")
print(shopping_cart)
position = shopping_cart.index("Laptop")
print("\nIndex of Laptop:")
print(position)
shopping_cart.clear()
print("\nAfter clear:")
print(shopping_cart)